### ISSUE TITLE
Civic Hall  TO Presentation

### ISSUE THREAD

**Issue by ultush** [tomeshnet/toronto-community-network#122]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** 02/03/2021
🎯 **Success criteria:** Design and deliver presentation at Civic Hall TO meeting
❌ **Blocked by:** 
👈 **Depends on:**

- Design and deliver presentation at Civic Hall TO meeting Feb/Mar 2021 
- 45 mins plus Q&A 
- 12 pm to 1 pm
- Audience: Civic Techies and Municipalities
- Platform: Webex
- Use CTTO presentation as a template

Main Contact: @maghdaee (who works at Civic Hall TO)

## Todo
- [x] Confirm speaker - Candidates: @TimTor 
- [x] Prepare presentation content and slide

**Comment by ultush** [comment]
@maghdaee Is the time of presentation (e.g. morning, afternoon, evening) flexible?

**Comment by maghdaee** [comment]
> @maghdaee Is the time of presentation (e.g. morning, afternoon, evening) flexible?

It's at noon . 12-1pm. Experience shows we get the best turnout.

**Comment by maghdaee** [comment]
Marzie will propose a few dates in Feb and March by next week meeting (Dec 13th).

**Comment by YurkoWasHere** [comment]
@maghdaee  in chat
ToMesh webinar at Civic Hall To- we can confirm Feb 3rd, 12-1pm if it works for presenters.

**Comment by maghdaee** [comment]
**Presenter(s):** Hank will be the main presenter in this session. Tim and Yurko will be attending to support with Q&A and discussion time. 

Presentation outline/ slide deck (in progress):
https://docs.google.com/presentation/d/1f5Sz-3VcwLLsT5ie_p95-tXhDNeiuM8GymKI6OGrmBU/edit?usp=sharing

Engagement: 
step 1: we'll look at questions raised by participants in CTTO session. 
https://cloud.tomesh.net/s/wE437PHQASoGELq
step2: we'll find a theme and select a few questions so that we can kick start the discussion. 
step3: we'll select/ draft 2-3 questions for polling/ Mentimeter. (marzie will be the responsible person for step 3)

What are the immediate next steps?
Presentation Rehearsal. 
When? next Wed (Jan 28), 6-6:45 PM. 
Where? on WebEx (let marzie know if you want to attend)
